-- ============================================================================
-- 06_ML_MODELS.SQL — ML Functions for Takaful Insurance Analytics
-- ============================================================================
USE DATABASE TAKAFUL_ANALYTICS;
USE SCHEMA ML;

-- ML.FORECAST: CLAIMS_RESERVE_FORECAST
CREATE OR REPLACE SNOWFLAKE.ML.FORECAST ML.CLAIMS_RESERVE_FORECAST(
  INPUT_DATA => SYSTEM$REFERENCE('TABLE', 'CURATED.IBNR_RESERVE'),
  SERIES_COLNAME => 'PRODUCT_LINE',
  TIMESTAMP_COLNAME => 'DS',
  TARGET_COLNAME => 'Y'
  
);

CREATE OR REPLACE TABLE ML.CLAIMS_RESERVE_FORECAST_RESULTS AS
SELECT * FROM TABLE(ML.CLAIMS_RESERVE_FORECAST!FORECAST(FORECASTING_PERIODS => 14));

-- ML.ANOMALY_DETECTION: FRAUD_DETECTION_MODEL
CREATE OR REPLACE SNOWFLAKE.ML.ANOMALY_DETECTION ML.FRAUD_DETECTION_MODEL(
  INPUT_DATA => SYSTEM$REFERENCE('TABLE', 'CURATED.FRAUD_RISK_SCORE'),
  SERIES_COLNAME => 'CLAIM_TYPE',
  TIMESTAMP_COLNAME => 'DS',
  TARGET_COLNAME => 'Y',
  LABEL_COLNAME => ''
);

CREATE OR REPLACE TABLE ML.FRAUD_DETECTION_MODEL_RESULTS AS
SELECT * FROM TABLE(ML.FRAUD_DETECTION_MODEL!DETECT_ANOMALIES(INPUT_DATA => SYSTEM$REFERENCE('TABLE', 'CURATED.FRAUD_RISK_SCORE'), SERIES_COLNAME => 'CLAIM_TYPE', TIMESTAMP_COLNAME => 'DS', TARGET_COLNAME => 'Y'));

