-- ============================================================================
-- 99_RESET.SQL — Reset Takaful Insurance Analytics to clean demo state
-- ============================================================================
USE DATABASE TAKAFUL_ANALYTICS;

-- Suspend tasks during demo
ALTER TASK IF EXISTS APP.TASK_REFRESH_CLAIMS SUSPEND;
ALTER TASK IF EXISTS APP.TASK_SCORE_FRAUD SUSPEND;
ALTER TASK IF EXISTS APP.TASK_FORECAST_RESERVES SUSPEND;

-- Force refresh Dynamic Tables
ALTER DYNAMIC TABLE CURATED.CLAIMS_DASHBOARD REFRESH;
ALTER DYNAMIC TABLE CURATED.COMBINED_RATIO REFRESH;
ALTER DYNAMIC TABLE CURATED.IBNR_RESERVE REFRESH;
ALTER DYNAMIC TABLE CURATED.FRAUD_RISK_SCORE REFRESH;

-- Verify key demo numbers
-- SELECT COUNT(*) FROM TAKAFUL_ANALYTICS.RAW.POLICIES → 200000
-- SELECT COUNT(*) FROM TAKAFUL_ANALYTICS.RAW.CLAIMS → 80000
-- SELECT COUNT(*) FROM TAKAFUL_ANALYTICS.RAW.CONTRIBUTIONS → 500000

-- Resume tasks
ALTER TASK IF EXISTS APP.TASK_FORECAST_RESERVES RESUME;
ALTER TASK IF EXISTS APP.TASK_SCORE_FRAUD RESUME;
ALTER TASK IF EXISTS APP.TASK_REFRESH_CLAIMS RESUME;
